<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Capacitor } from '@capacitor/core'
import { createGame, drawInitialHand, type Card, type GameRecord, type Player } from './game/game'
import { connectToRoom, listenAsHost, notifyPlayers, scanRooms, sendMessage, startHost, stopHost, type BluetoothMessage } from './bluetooth/ble'
type Screen = 'home'|'identity'|'lobby'|'game'|'result'|'history'|'detail'
const screen=ref<Screen>('home'), playerName=ref(''), localId=ref('local'), roomCode=ref(''), notice=ref('')
const bluetooth=ref<'disconnected'|'searching'|'connected'>('disconnected'), pendingPlayers=ref<Player[]>([]), players=ref<Player[]>([]), selectedCard=ref<string|null>(null), hand=ref<Card[]>([]), game=ref(createGame([])), history=ref<GameRecord[]>([]), selectedRecord=ref<GameRecord|null>(null)
const connectionDeviceId=ref('')
const connectedDevices=ref<Record<string,string>>({})
const aiThinking=ref(false)
const me=computed(()=>players.value.find(p=>p.id===localId.value)), isHost=computed(()=>me.value?.isHost??false), myTurn=computed(()=>game.value.turnPlayerId===localId.value)
const nextPlayer=computed(()=>{const i=players.value.findIndex(p=>p.id===localId.value);return players.value[(i+1)%Math.max(players.value.length,1)]})
const statusLabel=computed(()=>({disconnected:'Bluetooth desligado',searching:'Procurando dispositivos…',connected:'Bluetooth conectado'}[bluetooth.value]))
const letters=computed(()=> 'BURRO'.split('').map((letter,index)=>({letter,active:(me.value?.penalty??0)>index})))
onMounted(()=>{history.value=JSON.parse(localStorage.getItem('burro-history')??'[]');playerName.value=localStorage.getItem('burro-player-name')??''})
function persistHistory(){localStorage.setItem('burro-history',JSON.stringify(history.value))}
function flash(message:string){notice.value=message;window.setTimeout(()=>notice.value='',2800)}
function beginIdentity(){screen.value='identity'}
async function createRoom(){if(playerName.value.trim().length<2)return flash('Informe um nome com pelo menos 2 caracteres.');localStorage.setItem('burro-player-name',playerName.value.trim());localId.value=`p-${Date.now()}`;roomCode.value=String(Math.floor(1000+Math.random()*8999));players.value=[{id:localId.value,name:playerName.value.trim(),isHost:true,connected:true,penalty:0}];pendingPlayers.value=[];screen.value='lobby';try{await startHost(playerName.value.trim());await listenAsHost((message,deviceId)=>handleHostMessage(message,deviceId),deviceId=>{players.value=players.value.map(p=>p.id===deviceId?{...p,connected:false}:p);flash('Um jogador se desconectou.')});bluetooth.value='connected'}catch(error){bluetooth.value='disconnected';flash(`Bluetooth indisponível: ${error instanceof Error?error.message:'verifique as permissões'}`)}}
async function searchRoom(){if(playerName.value.trim().length<2)return flash('Informe seu nome antes de procurar.');localStorage.setItem('burro-player-name',playerName.value.trim());localId.value=`p-${Date.now()}`;players.value=[{id:localId.value,name:playerName.value.trim(),isHost:false,connected:true,penalty:0}];pendingPlayers.value=[];screen.value='lobby';bluetooth.value='searching';try{await scanRooms(async room=>{if(connectionDeviceId.value)return;connectionDeviceId.value=room.deviceId;roomCode.value=room.name.replace('JEGUE-','').slice(0,12);await connectToRoom(room.deviceId,localId.value,message=>handleClientMessage(message),()=>{bluetooth.value='disconnected';flash('Conexão Bluetooth perdida.')});bluetooth.value='connected';flash(`Conectado à sala ${roomCode.value}.`)})}catch(error){bluetooth.value='disconnected';flash(`Não foi possível procurar: ${error instanceof Error?error.message:'verifique o Bluetooth'}`)}}
function simulateRequest(){if(!pendingPlayers.value.length)pendingPlayers.value.push({id:'p-visitor',name:'Ana (simulação)',isHost:false,connected:true,penalty:0})}
async function acceptPlayer(){players.value.push(...pendingPlayers.value);pendingPlayers.value=[];await notifyPlayers(localId.value,'JOGADOR_ENTROU',{players:players.value});flash('Jogador aceito na sala.')}
async function startGame(){if(players.value.length<2)return flash('A partida precisa de pelo menos 2 jogadores.');game.value=createGame(players.value);hand.value=drawInitialHand(game.value,localId.value);selectedCard.value=null;for(const player of players.value.filter(p=>p.id!==localId.value)){const deviceId=connectedDevices.value[player.id];if(deviceId)await notifyPlayers(localId.value,'PARTIDA_INICIADA',{turnPlayerId:game.value.turnPlayerId,players:players.value,hand:drawInitialHand(game.value,player.id)},deviceId)}screen.value='game'}
function chooseCard(card:Card){if(!myTurn.value)return flash('Aguarde sua vez.');selectedCard.value=selectedCard.value===card.id?null:card.id}
async function sendCard(){if(!selectedCard.value||aiThinking.value)return flash('Selecione uma carta para enviar.');const card=hand.value.find(c=>c.id===selectedCard.value);if(!card)return;hand.value=hand.value.filter(c=>c.id!==card.id);selectedCard.value=null;const simulated=Capacitor.getPlatform()==='web'||players.value.some(p=>p.id==='p-visitor');game.value.turnPlayerId=simulated?'ai':(nextPlayer.value?.id??localId.value);game.value.round++;if(!simulated){if(connectionDeviceId.value)await sendMessage(connectionDeviceId.value,localId.value,'JOGADA',{cardId:card.id,turnPlayerId:game.value.turnPlayerId});else await notifyPlayers(localId.value,'JOGADA',{cardId:card.id,turnPlayerId:game.value.turnPlayerId})}if(simulated){aiThinking.value=true;flash('Ana recebeu sua carta e está escolhendo uma para devolver…');window.setTimeout(()=>{const values=['7','Q','A','K'];const suits=['♣','♦','♥','♠'];hand.value.push({id:`ana-${Date.now()}`,value:values[Math.floor(Math.random()*values.length)],suit:suits[Math.floor(Math.random()*suits.length)] as Card['suit']});game.value.turnPlayerId=localId.value;aiThinking.value=false;if(game.value.round>=3)finishGame(true);else flash('Ana devolveu uma carta. Sua vez novamente!')},850)}else{hand.value.push({...card,id:`${card.id}-received`});if(game.value.round>=3)finishGame(true);else flash(`Carta enviada para ${nextPlayer.value?.name??'o próximo jogador'}.`)}}
function handleHostMessage(message:BluetoothMessage,deviceId:string){if(message.type==='SOLICITACAO_ENTRADA'){const name=String(message.payload.name??'Jogador');connectedDevices.value[message.senderId]=deviceId;if(!pendingPlayers.value.some(p=>p.id===message.senderId))pendingPlayers.value.push({id:message.senderId,name,isHost:false,connected:true,penalty:0});connectionDeviceId.value=deviceId} }
function handleClientMessage(message:BluetoothMessage){if(message.type==='JOGADOR_ENTROU'&&Array.isArray(message.payload.players))players.value=message.payload.players as Player[];if(message.type==='PARTIDA_INICIADA'){game.value.turnPlayerId=String(message.payload.turnPlayerId);if(Array.isArray(message.payload.players))players.value=message.payload.players as Player[];if(Array.isArray(message.payload.hand))hand.value=message.payload.hand as Card[];screen.value='game'}if(message.type==='PARTIDA_FINALIZADA')flash('A partida terminou.')}
function finishGame(won:boolean){const record:GameRecord={id:`match-${Date.now()}`,startedAt:game.value.startedAt,endedAt:new Date().toISOString(),players:players.value,winnerId:won?localId.value:players.value[0].id,penalizedId:won?(players.value.find(p=>p.id!==localId.value)?.id??localId.value):localId.value,rounds:game.value.round,status:'finalizada',reason:won?'Grupo de quatro cartas iguais':'Partida encerrada',localResult:won?'Vencedor':'Participante'};history.value.unshift(record);persistHistory();screen.value='result'}
function openRecord(r:GameRecord){selectedRecord.value=r;screen.value='detail'}
function deleteRecord(id:string){if(confirm('Excluir esta partida do histórico?')){history.value=history.value.filter(r=>r.id!==id);persistHistory()}}
function clearHistory(){if(confirm('Apagar todo o histórico?')){history.value=[];persistHistory()}}
async function leave(){await stopHost();screen.value='home';bluetooth.value='disconnected';players.value=[];connectionDeviceId.value=''}
</script>
<template>
<main class="app-shell"><header class="topbar"><button v-if="screen!=='home'" class="icon-button" @click="screen=screen==='detail'?'history':'home'">←</button><div class="brand"><span class="brand-mark">♞</span><span>JEGUE</span></div><button class="history-link" @click="screen='history'">Histórico</button></header>
<section v-if="screen==='home'" class="screen hero-screen"><div class="hero-art"><span>♞</span><i>♣</i><b>♦</b></div><p class="eyebrow">JOGO DE CARTAS OFFLINE</p><h1>Quem vai ser o<br><em>JEGUE?</em></h1><p class="muted intro">Forme seu grupo de quatro cartas antes dos adversários. Jogue perto dos seus amigos, sem internet.</p><button class="primary full" @click="beginIdentity">Começar partida <span>→</span></button><button class="secondary full" @click="screen='history'">Ver histórico <span>↗</span></button><div class="feature-row"><span>♧ <small>Bluetooth</small></span><span>◈ <small>Offline</small></span><span>♣ <small>2–6 jogadores</small></span></div></section>
<section v-else-if="screen==='identity'" class="screen centered"><p class="eyebrow">ANTES DE COMEÇAR</p><h2>Como podemos<br><em>te chamar?</em></h2><p class="muted">Seu nome aparecerá para os jogadores da sala.</p><label class="field-label">SEU NOME<input v-model="playerName" maxlength="18" placeholder="Ex.: Henrique" @keyup.enter="createRoom"></label><button class="primary full" @click="createRoom">Criar uma sala <span>→</span></button><button class="secondary full" @click="searchRoom">Procurar uma sala <span>⌕</span></button><p class="tiny">Ao criar uma sala, você será o anfitrião.</p></section>
<section v-else-if="screen==='lobby'" class="screen"><p class="eyebrow">SALA DE ESPERA · #{{roomCode}}</p><div class="title-line"><div><h2>Junte sua <em>galera.</em></h2><p class="muted">Compartilhe o código ou aguarde no Bluetooth.</p></div><span class="connection" :class="bluetooth">● {{statusLabel}}</span></div><div class="room-code"><small>CÓDIGO DA SALA</small><strong>{{roomCode}}</strong><span>Toque para copiar</span></div><div class="panel"><div class="panel-title"><b>Jogadores conectados</b><span>{{players.length}}/6</span></div><div v-for="player in players" :key="player.id" class="player-row"><span class="avatar">{{player.name.charAt(0)}}</span><span>{{player.name}} <small v-if="player.isHost">HOST</small></span><i>●</i></div><div v-if="pendingPlayers.length" class="request"><span class="avatar">A</span><span>Ana quer entrar</span><button class="mini" @click="acceptPlayer">Aceitar</button></div><button v-if="isHost&&!pendingPlayers.length" class="ghost-button" @click="simulateRequest">＋ Simular jogador próximo</button></div><button class="primary full" :disabled="players.length<2" @click="startGame">Começar partida <span>→</span></button><p v-if="players.length<2" class="hint">Aguardando pelo menos mais um jogador</p><button class="text-button" @click="leave">Sair da sala</button></section>
<section v-else-if="screen==='game'" class="screen game-screen"><div class="game-head"><div><p class="eyebrow">RODADA {{game.round+1}}</p><h2>Sua vez, <em>{{playerName}}.</em></h2></div><span class="connection connected">● Conectado</span></div><div class="turn-card"><span class="turn-icon">↻</span><div><small>PRÓXIMO PASSO</small><p>Envie uma carta para <strong>{{nextPlayer?.name}}</strong></p></div></div><div class="opponents"><div v-for="player in players.filter(p=>p.id!==localId)" :key="player.id" class="opponent"><span class="avatar small-avatar">{{player.name.charAt(0)}}</span><span>{{player.name}}</span><small>{{player.penalty?'BURRO'.slice(0,player.penalty):'jogando'}}</small></div></div><div class="cards-title"><b>Sua mão</b><small>Escolha uma carta</small></div><div class="hand"><button v-for="card in hand" :key="card.id" class="playing-card" :class="[{selected:selectedCard===card.id},`suit-${card.suit}`]" @click="chooseCard(card)"><span>{{card.value}}</span><strong>{{card.suit}}</strong><span>{{card.value}}</span></button></div><button class="primary full" :disabled="!selectedCard||!myTurn" @click="sendCard">Enviar carta <span>→</span></button><div class="burro"><small>SUA PONTUAÇÃO</small><span v-for="item in letters" :key="item.letter" :class="{active:item.active}">{{item.letter}}</span></div></section>
<section v-else-if="screen==='result'" class="screen centered"><div class="result-badge">♞</div><p class="eyebrow">PARTIDA ENCERRADA</p><h2>Você foi o<br><em>vencedor!</em></h2><p class="muted">Grupo de quatro cartas iguais formado.</p><div class="result-panel"><span>🏆</span><div><b>{{playerName}}</b><small>Vencedor da partida</small></div><strong>0 letras</strong></div><button class="primary full" @click="screen='history'">Ver histórico <span>→</span></button><button class="secondary full" @click="leave">Voltar ao início</button></section>
<section v-else-if="screen==='history'" class="screen"><p class="eyebrow">SUAS PARTIDAS</p><div class="title-line"><div><h2>Histórico</h2><p class="muted">Tudo fica salvo neste dispositivo.</p></div><button v-if="history.length" class="clear-button" @click="clearHistory">Limpar</button></div><div v-if="!history.length" class="empty"><span>♧</span><h3>Nenhuma partida ainda</h3><p class="muted">Suas vitórias e partidas interrompidas aparecerão aqui.</p><button class="primary" @click="beginIdentity">Jogar agora →</button></div><div v-for="record in history" :key="record.id" class="history-item" @click="openRecord(record)"><span class="history-icon">♞</span><div><b>{{record.localResult}}</b><small>{{new Date(record.endedAt).toLocaleDateString('pt-BR')}} · {{record.players.length}} jogadores</small></div><strong>{{record.winnerId===localId?'Vitória':'Partida'}}</strong><button class="delete" @click.stop="deleteRecord(record.id)">×</button></div></section>
<section v-else class="screen"><p class="eyebrow">DETALHES DA PARTIDA</p><h2>{{selectedRecord?.localResult}}</h2><p class="muted">{{selectedRecord&&new Date(selectedRecord.endedAt).toLocaleString('pt-BR')}}</p><div class="detail-grid"><div><small>RODADAS</small><b>{{selectedRecord?.rounds}}</b></div><div><small>STATUS</small><b>{{selectedRecord?.status}}</b></div></div><div class="panel"><div class="panel-title"><b>Participantes</b></div><div v-for="player in selectedRecord?.players" :key="player.id" class="player-row"><span class="avatar">{{player.name.charAt(0)}}</span><span>{{player.name}}</span><strong v-if="player.id===selectedRecord?.winnerId">🏆</strong></div></div><button class="secondary full" @click="screen='history'">← Voltar ao histórico</button></section><div v-if="notice" class="toast">{{notice}}</div></main>
</template>
